name: Installer ISO
on:
  release:
    types:
      - published

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Install nix
        uses: cachix/install-nix-action@v25
        with:
          extra_nix_config: "extra-experimental-features = nix-command flakes"

      - name: Set up cachix
        uses: cachix/cachix-action@v13
        with:
          name: tie-infra
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          skipPush: true

      - name: Build image
        run: nix build "${installable}"
        env:
          installable: "github:${{ github.repository }}/${{ github.sha }}#installer-iso-x86_64-linux"

      - name: Release image
        run: gh release upload --clobber -R="${GITHUB_REPOSITORY}" "${tag_name}" result/iso/*.iso
        env:
          tag_name: ${{ github.event.release.tag_name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
