name: Installer ISO
on:
  release:
    types:
      - published

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Install nix
        uses: cachix/install-nix-action@v21
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up cachix
        uses: cachix/cachix-action@v12
        with:
          name: yamporg
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build image
        run: nix build "${installable}"
        env:
          installable: "github:${{ github.repository }}/${{ github.sha }}#installer-x86-64-iso"

      - name: Release image
        run: gh release upload --clobber -R="${GITHUB_REPOSITORY}" "${tag_name}" result/iso/*.iso
        env:
          tag_name: ${{ github.event.release.tag_name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
